# -*- coding: utf-8 -*-
"""Roshambo Or Rock Paper Scissor Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1znFhKtNIKI69i7DyyOqDs2hLgEcnX2wa

Roshambo Or Rock Paper Scissor Game
    Rules: Rock smashes scissors.
    Paper covers rock.
    Scissors cut paper.

Intro to Python Final Project by Valeri Paul
"""

import random

while True:
  #User Input
  user_action = input("Type in a choice from (rock, paper, scissors) all lower case\n & click Enter button:  ")

#Define the choices & use random function
  possible_action = ["rock", "paper", "scissors"]
  computer_action = random.choice(possible_action)

  print(f"\nYour choice is {user_action}. The computer randomly selected {computer_action}.\n Go to next to find out who Won!")

#Determine a Winner!
  if user_action == computer_action:
    print(f"Both Players selected {user_action}. Tie!  Try Again.")
  elif user_action == "rock":
    if computer_action == "scissors":
      print("Rock smashes Scissors. You Win!")
    else:
      print("Paper covers Rock!  You Lose!")
  elif user_action == "paper":
    if computer_action == "rock":
      print("Paper covers Rock! You Win!")
    else:
      print("Scissors cuts Paper! You Lose!")
  elif user_action == "scissors":
    if computer_action == "paper":
      print("Scissors cuts Paper! You Win!")
    else:
      print("Rock smashes Scissors! You Lose!")
  else:
    print("Your choice", (user_action), "doesn't exist!  You Lose!")

  play_again = input("Play again?  (y/n):  ")
  if play_again.lower() != "y":
    break